import type { BlogPost } from '@/types';

export const MOCK_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Ferrari LaFerrari Aperta Final Edition: The Last Naturally Aspirated V12',
    slug: 'ferrari-laferrari-aperta-final-edition',
    excerpt: 'There are fast cars, there are beautiful cars, and then there is this — a machine so singular in purpose it transcends mere transportation.',
    content: '',
    category: 'Cars',
    author: 'Alessandro Greco',
    publishedAt: '2026-04-10',
    imageUrl: '/images/placeholder-car.jpg',
    featured: true,
    readTime: 8,
  },
  {
    id: '2',
    title: 'Patek Philippe 5711: Why It Still Commands Six Figures in 2026',
    slug: 'patek-philippe-5711-value-2026',
    excerpt: 'Discontinued, yet more coveted than ever. The Nautilus 5711 remains the watch market\'s most enduring paradox.',
    content: '',
    category: 'Watches',
    author: 'M. Laurent',
    publishedAt: '2026-04-08',
    imageUrl: '/images/placeholder-watch.jpg',
    featured: true,
    readTime: 6,
  },
  {
    id: '3',
    title: 'Aboard the Benetti 107: A Week in the Mediterranean',
    slug: 'benetti-107-mediterranean-week',
    excerpt: '107 feet. 5 staterooms. One ocean. The Benetti Classic Supreme redefines what a holiday can mean.',
    content: '',
    category: 'Yachts',
    author: 'R. Voss',
    publishedAt: '2026-04-06',
    imageUrl: '/images/placeholder-yacht.jpg',
    featured: true,
    readTime: 10,
  },
  {
    id: '4',
    title: 'Inside Zuma Dubai: The Ultimate Food & Cocktail Guide',
    slug: 'zuma-dubai-food-cocktail-guide',
    excerpt: 'Contemporary Japanese robatayaki in the heart of the Dubai International Financial Centre.',
    content: '',
    category: 'Food & Drink',
    author: 'S. Chen',
    publishedAt: '2026-04-04',
    imageUrl: '/images/placeholder-food.jpg',
    featured: false,
    readTime: 5,
  },
  {
    id: '5',
    title: 'Maldives vs Seychelles: Where the Discerning Traveller Should Go in 2026',
    slug: 'maldives-vs-seychelles-2026',
    excerpt: 'Two island paradises, two entirely different philosophies. Our editors have stayed at both.',
    content: '',
    category: 'Travel',
    author: 'P. Black',
    publishedAt: '2026-03-30',
    imageUrl: '/images/placeholder-travel.jpg',
    featured: false,
    readTime: 7,
  },
  {
    id: '6',
    title: 'Tom Ford vs Brunello Cucinelli: The Definitive Style Guide',
    slug: 'tom-ford-vs-brunello-cucinelli-style-guide',
    excerpt: 'Two titans of menswear, two completely opposing visions of luxury. Which house speaks to your wardrobe?',
    content: '',
    category: 'Style',
    author: 'J. White',
    publishedAt: '2026-03-28',
    imageUrl: '/images/placeholder-style.jpg',
    featured: false,
    readTime: 6,
  },
];
